[package]
name = "type_analysis"
version = "2.1.9"
authors = ["Costa Group UCM", "iden3"]
edition = "2018"

[dependencies]
program_structure = { path = "../program_structure" }
num-bigint-dig = { workspace = true }
num-traits = { workspace = true }
