[package]
name = "code_producers"
version = "2.1.9"
authors = ["Costa Group UCM", "iden3"]
edition = "2018"

[dependencies]
handlebars = { workspace = true }
lz_fnv = { workspace = true }
num-bigint-dig = { workspace = true }
serde_json = { workspace = true }
