[package]
name = "circom_algebra"
version = "2.1.4"
authors = ["Costa Group UCM", "iden3"]
edition = "2018"

[dependencies]
num-bigint-dig = { workspace = true }
num-traits = { workspace = true }
constant_tracking = { path = "../constant_tracking" }
